# Generated by Django 5.1.4 on 2025-01-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
