# Generated by Django 5.1.6 on 2025-02-26 19:16

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=55)),
                ('amount', models.PositiveIntegerField()),
                ('due_date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 2, 26, 19, 16, 49, 457291, tzinfo=datetime.timezone.utc))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('pending_payment', 'Pending Payment')], max_length=55)),
                ('final_price', models.PositiveBigIntegerField()),
                ('discount', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='Order.discount')),
                ('item', models.ManyToManyField(to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='Order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
