# Generated by Django 5.1.6 on 2025-02-26 19:43

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 2, 26, 19, 43, 15, 908137, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Order.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(through='Order.OrderProduct', to='Product.product'),
        ),
    ]
