# Generated by Django 5.1.6 on 2025-02-26 19:56

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_discount_due_date'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 2, 26, 19, 56, 33, 853173, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(related_name='orders', through='Order.OrderProduct', to='Product.product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='Order.order'),
        ),
    ]
