# Generated by Django 5.1.6 on 2025-02-28 19:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_discount_due_date_alter_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 2, 28, 19, 48, 8, 454194, tzinfo=datetime.timezone.utc))]),
        ),
    ]
